# Generated by Django 5.0.7 on 2024-09-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='schedule',
            field=models.TextField(blank=True),
        ),
    ]
