# Generated by Django 5.0.7 on 2024-09-19 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='schedule',
        ),
        migrations.AddField(
            model_name='doctorclinicaffiliation',
            name='working_schedule',
            field=models.TextField(blank=True),
        ),
    ]
